services:
  deserialization_pickle_bookmarks:
    build:
      context: ./app
      args:
      - FLAG
    ports:
    - 80
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:80/
      timeout: 5s
      retries: 30
      interval: 5s
