services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
    - 5003:5003
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:5003
      interval: 5s
      retries: 30
      timeout: 5s
